name: Compile Factorizer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.2.2'  # ä¾‹: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc python3-dev

    - name: Compile factorizer.so
      run: |
        gcc -c factorizer.c -o factorizer.o $(python3-config --cflags) -fPIC
        gcc -shared -o factorizer.so factorizer.o $(python3-config --ldflags)

    - name: Create target directory
      run: mkdir -p /opt/render/project/src/

    - name: Move factorizer.so to project directory
      run: mv factorizer.so /opt/render/project/src/

    - name: Upload compiled file
      uses: actions/upload-artifact@v3
      with:
        name: factorizer-so
        path: /opt/render/project/src/factorizer.so
